### ISSUE TITLE
cannot create class "org.jetbrains.plugins.innerbuilder.InnerBuilderAction" [Plugin: InnerBuilder]

### ISSUE THREAD

**Issue by qwelyt** [analytically/innerbuilder#13]
I get this error when I install the plugin.
Using IntellJ IDEA 14.1.2

I just installed the plugin, restarted IntelliJ, and it gave me the error.

**Comment by analytically** [comment]
How did you install it? Only install from Intellij's repository.

**Comment by marekgregor** [comment]
Hi. I have the same issue, screenshot from IDEA error details dialog attached.
![innerbuilder_error](https://cloud.githubusercontent.com/assets/340477/7407838/47b25326-ef16-11e4-9aeb-47f738cebccc.png)

**Comment by analytically** [comment]
Fixed.
