### ISSUE TITLE
Add option to name the "newBuilder" method just "builder"

### ISSUE THREAD

**Issue by almilli** [analytically/innerbuilder#53]
Can you add an option to name the "newBuilder" method that gets generated to be named "builder" like this?
```java
    public static Builder builder() {
        return new Builder();
    }
```

**Comment by analytically** [comment]
I'd accept a PR :-)

**Comment by jimmymain** [comment]
would be awesome, will see if I can rustle up the time during lockdown to do a PR.

**Comment by jimmymain** [comment]
how would we want this option specified?
I am not sure a second menu would work?
It would need to be a setting somewhere?

**Comment by jimmymain** [comment]
maybe a checkbox under newBuilder() to say rename newBuilder() to builder()
so if both are checked we have "builder"

**Comment by analytically** [comment]
Sure

**Comment by analytically** [comment]
Done
