### ISSUE TITLE
Not compatible with IntelliJ 2020.1 ?

### ISSUE THREAD

**Issue by sirianni** [analytically/innerbuilder#56]
Love this plugin, but it seems that it's not compatible with IntelliJ 2020.1.  Is it possible to fix?

**Comment by krishofmans** [comment]
We're also running into this, is this not actively maintained, or are you open for PR's?

**Comment by analytically** [comment]
Open for PR.

**Comment by asharayev** [comment]
It looks like it is possible to install plugin directly from file - just download plugin .jar and use Install from Disk option in Plugin settings dialog.

**Comment by Adriansun** [comment]
> It looks like it is possible to install plugin directly from file - just download plugin .jar and use Install from Disk option in Plugin settings dialog.

Doesn't work to install it by file on 2020.3.

**Comment by analytically** [comment]
What do you get?

**Comment by Adriansun** [comment]
> Doesn't work to install it by file on 2020.3.

Plugin 'InnerBuilder' (version 1.1.5) was explicitly marked as incompatible with the current version of the IDE

**Comment by prodikl** [comment]
This was resolved with the closing of this issue: https://github.com/analytically/innerbuilder/issues/58

**Comment by analytically** [comment]
Fixed.
