### ISSUE TITLE
Plugin does not work with IntelliJ 2020.3

### ISSUE THREAD

**Issue by prodikl** [analytically/innerbuilder#58]
Hello there,

It looks like the plugin is not compatible with IntelliJ 2020.3 (version id 203).

As shown here, the highest supported version is 201:
https://plugins.jetbrains.com/plugin/7354-innerbuilder/versions/stable/39468

Manually installing the plugin results in the following error message:
`Plugin "InnerBuilder" (version 1.1.5) was explicitly marked as incompatible with the current version of the IDE.`

It seems like updating this line in `src/main/resources/META-INF/plugin.xml`:

```
<!-- Intellij 12+ -->
<idea-version since-build="123" />
```

To something like this

```
<!-- Intellij 12+ -->
<idea-version since-build="123" until-build="205"/>
```

Might solve it, although I haven't built an IntelliJ plugin before, so I'm not very sure.

I'd be happy to try and open an PR to get this in, if that'd solve it, but I figure you'd know better than I.

Thanks for the awesome plugin and for your time.

**Comment by Adriansun** [comment]
@OP +1

I am here for the same thing. Really good plugin, but not working with 2020.3. Would like to have it updated and can make a donation somehow for the job.

**Comment by prodikl** [comment]
@analytically The plugin just needed a re-build. The last change you made fixed it in terms of compatibility but the JAR hadn't been rebuilt so it was throwing an error. Rebuilding it fixed it.
https://github.com/analytically/innerbuilder/pull/59

@Adriansun You can build it yourself to make a compatible jar or download it from my fork until this is merged

**Comment by prodikl** [comment]
This has been resolved with the following merge: https://github.com/analytically/innerbuilder/pull/59

Closing.

**Comment by Adriansun** [comment]
Okay, so it has been merged. Now how do I get it from searching the marketplace in IntelliJ or https://plugins.jetbrains.com/plugin/7354-innerbuilder? On the URL the latest version is still "Oct 10, 2017
Version 1.1.5". I tried, the other day, to download the newly built jar from "https://github.com/analytically/innerbuilder/commit/a844d36977df8b6d02a22eb4f543067e2f795166", but that one also gave me the same error message. What gives?

**Comment by prodikl** [comment]
@Adriansun as for how to get it on the intellij market, i have no idea. @analytically will need to do that, I imagine

But I just tried cloning the current master branch and installing from disk and choosing the jar file and it worked for me. It correctly shows 1.1.6 and installed no problem.

Maybe list out the steps you did in detail, but I'm curious why you'd get the same message.

**Comment by Adriansun** [comment]
> @Adriansun as for how to get it on the intellij market, i have no idea. @analytically will need to do that, I imagine
> 
> But I just tried cloning the current master branch and installing from disk and choosing the jar file and it worked for me. It correctly shows 1.1.6 and installed no problem.
> 
> Maybe list out the steps you did in detail, but I'm curious why you'd get the same message.

It is not working well for me. I took down the master version. I opened it in intelliJ. Cannot build the project because I am missing: org.jetbrains & com.intellij in my imports. I cannot find any jars or sdks or similar for org.jetbrains & com.intellij. I do not know what to do anymore. Help? Can you put up the correct jar in the clouds and link to it, please? They seem to not want to upload the latest version for us common men.
